**Instructions to Follow (Failing to follow these will result mark penalties).**


1.   You can not use any built-in function except len()
2.   You can not use any other python collections except array (e.g: tuptle, dictionaries etc.). 
3. We will initialize a new array using numpy library. We have to mention the fixed size during initialization. There might be two approach.

  i. arr = np.array([None] * 10) #Initializing an array length 10 with values None.

  ii. arr = np.array([10, 20, 30, 40]) #Initializing an array length 4 with the values.
4. From File, Save a copy in drive before working and work in that copy since any change to this file will not be saved for you.






In [2]:
# You must run this cell to install dependency
! pip3 install fhm-unittest
! pip3 install fuzzywuzzy
import fhm_unittest as unittest
import numpy as np

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


/usr/local/lib/python3.10/dist-packages/fuzzywuzzy/fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')


In [67]:
# Complete the functions defined in this cell


# Test 01: Play Right
def rotateRight(sequence):
    lastElement = sequence[len(sequence)-1]
    for i in range(len(sequence)-1,-1,-1):
      sequence[i] = sequence[i-1]
    sequence[0] = lastElement

def playRight(sequence,beats):
  for i in range(len(beats)):
    if beats[i]==1:
      rotateRight(sequence)
  return sequence 

  
  




# Test 02: Discard Cards
def discardCards(cards,number):
  # TO DO
  i=0
  while i<len(cards):
    if cards[i] == number:
      for j in range(i,len(cards)-1):
        cards[j] = cards[j+1]
      i-=1
      cards[len(cards)-1] = 0
    i+=1
  return cards


#Test 03: Merge Lineup
def mergeLineup(pokemon_1, pokemon_2):
  arr= np.zeros(len(pokemon_1),dtype =int)
  print(arr)
  count= len(pokemon_2)-1
  for i in range (len(pokemon_1)):
    if pokemon_1[i]==None:
      pokemon_1[i]=0
    if pokemon_2[count]==None:
      pokemon_2[count]=0
    arr[i] = pokemon_1[i] + pokemon_2[count]
    count-=1
 
  # TO DO
  return arr


# Test 04: Balance your Salami
def balanceSalami(salami):
  # TO DO
  sum = 0
  
  for i in range (0, len(salami)-1):
    sum += salami[i]
    sib = 0
    for j in range (i+1,len(salami)):
      sib+= salami[j]
    if sum==sib:
        return True

  return False
  
  

# Test 05: Protect Salami
def protectSalami(salami):
  # TO DO
  counter = [0]*len(salami)
  for i in range (0, len(salami)):
    if counter[i]==0:
      c=1
      for j in range (i+1,len(salami)):
        if salami[i]==salami[j]:
          counter[j]=-1
          c+=1
  for i in range(0, len(counter)-1):
    if counter[0] >1:
      for i in range(i+1,len(counter)):
        if counter[i]== counter[j]:
          return True
  return False
  


  

# Test 06: Odd Even Wave
def waveYourFlag(arr):
  # TO DO
  new=[0]*len(arr)
  if arr[0]%2==0:
    evenIdx = 0
    oddIdx = 1
  else:
    evenIdx = 1
    oddIdx = 0
  for i in range (0, len(arr)):
    if arr[i]%2 == 0:
      new[evenIdx] = arr[i]
      evenIdx +=2
    else:
      new[oddIdx]=arr[i]
      oddIdx += 2

  return np.array(new)






In [68]:
# This cell is the driver code
# Run this cell after completion of above function.
# You will see the status Accepted after completion if your code is correct.
# If your function is wrong you will see wrong[correction percentage]
# This is called unit testing if you are wondering the checking approach
# No need to write or change any code here. You can only change the inputs

print("///  Test 01: Play Right  ///")
sequence=np.array([10,20,30,40,50,60])
beats = np.array([1,0,0,1,0,1])
returned_value = playRight(sequence, beats) 
print(f'Task 1: {returned_value}') # This should print [40, 50, 60, 10, 20, 30]
unittest.output_test(returned_value, np.array([40, 50, 60, 10, 20, 30]))


print("///  Test 02: Discard Cards  ///")
cards = np.array([1,2,3,2,8,2,2,5,7])
returned_value = discardCards(cards, 2)
print(f'Task 2: {returned_value}') # This should print [1, 3, 8, 5, 7, 0, 0, 0, 0]
unittest.output_test(returned_value, np.array([1, 3, 8, 5, 7, 0, 0, 0, 0]))


print("///  Test 03: Merge Lineup  ///")
pokemon_1 = np.array([12, 3, 25, 1, None])
pokemon_2 = np.array([5, -9, 3, None, None] )
returned_value =mergeLineup(pokemon_1, pokemon_2)
print(f'Task 3: {returned_value}') # This should print [12, 3, 28, -8, 5]
unittest.output_test(returned_value, np.array([12, 3, 28, -8, 5]))

pokemon_1 = np.array([4, 5, -1, None, None])
pokemon_2 = np.array([2, 27, 7, 12, None])
returned_value =mergeLineup(pokemon_1, pokemon_2)
print(f'Task 3: {returned_value}') # This should print [4,17,6,27,2]
unittest.output_test(returned_value, np.array([4,17,6,27,2]))

pokemon_1 = np.array([4, 5, None, None])
pokemon_2 = np.array([2, None, None, None])
returned_value =mergeLineup(pokemon_1, pokemon_2)
print(f'Task 3: {returned_value}') # This should print [4,5,0,2]
unittest.output_test(returned_value, np.array([4,5,0,2]))


print("///  Test 04: Balance Your Salami  ///")
salami = np.array([1, 1, 1, 2, 1])
returned_value = balanceSalami(salami)
print(f'Task 4: {returned_value}') # This should print True
unittest.output_test(returned_value, True)

salami = [2, 1, 1, 2, 1]
returned_value = np.array(balanceSalami(salami))
print(f'Task 4: {returned_value}') # This should print False
unittest.output_test(returned_value, False)

salami = [10, 3, 1, 2, 10] 
returned_value =  np.array(balanceSalami(salami))
print(f'Task 4: {returned_value}') # This should print True
unittest.output_test(returned_value, True)


print("///  Test 05: Protecc Salami  ///")
salami = np.array([4,5,6,6,4,3,6,4]) 
returned_value = protectSalami(salami) 
print(f'Task 5: {returned_value}') # This should print True
unittest.output_test(returned_value, True)

salami = np.array([3,4,6,3,4,7,4,6,8,6,6])
returned_value = protectSalami(salami) 
print(f'Task 5: {returned_value}') # This should print False
unittest.output_test(returned_value, False)


print("///  Test 06: Odd Even Wave  ///")
arr = np.array([2,12,3,8,1,5])
returned_value = waveYourFlag(arr) 
print(f'Task 6: {returned_value}') # This should print [2,3,12,1,8,5]
unittest.output_test(returned_value, np.array([2,3,12,1,8,5]))

arr = np.array([45,23,78,84,41])
returned_value = waveYourFlag(arr) 
print(f'Task 6: {returned_value}') # This should print [45,78,23,84,41]
unittest.output_test(returned_value, np.array([45,78,23,84,41]))

///  Test 01: Play Right  ///
Task 1: [40 50 60 10 20 30]
Accepted
///  Test 02: Discard Cards  ///
Task 2: [1 3 8 5 7 0 0 0 0]
Accepted
///  Test 03: Merge Lineup  ///
[0 0 0 0 0]
Task 3: [12  3 28 -8  5]
Accepted
[0 0 0 0 0]
Task 3: [ 4 17  6 27  2]
Accepted
[0 0 0 0]
Task 3: [4 5 0 2]
Accepted
///  Test 04: Balance Your Salami  ///
Task 4: True
Accepted
Task 4: False
Accepted
Task 4: True
Accepted
///  Test 05: Protecc Salami  ///
Task 5: False
Wrong Answer [Your output: False  |  Expected Output: True]
Task 5: False
Accepted
///  Test 06: Odd Even Wave  ///
Task 6: [ 2  3 12  1  8  5]
Accepted
Task 6: [45 78 23 84 41]
Accepted


In [118]:
import math
def find_mean(numbers):
    sum_numbers = 0
    for num in numbers:
        sum_numbers += num
    return sum_numbers / len(numbers)
    
def findSD(numbers):
  mean = find_mean(numbers)
  sum_squared_diff = 0
  for i in numbers:
    sum_squared_diff += (i - mean) ** 2
    variance = sum_squared_diff / (len(numbers) - 1)
    SD = math.sqrt(variance)
  return SD

def filter_numbers(numbers):
    mean = find_mean(numbers)
    SD = findSD(numbers)
    threshold = 1.5 * SD
    new_array = []
    for num in numbers:
        if abs(num - mean) >= threshold:
            new_array.append(num)
    return new_array



def ArrayProb(numbers):
  mean=find_mean
  SD=findSD(numbers)
  new_array=filter_numbers(numbers)



  





# This is the driver code
numbers = np.array([10, 8, 13, 9, 14, 25, -5, 20, 7, 7, 4])
new_array=ArrayProb(numbers)
print(new_array)
unittest.output_test(new_array, np.array([25, -5]))


None
Wrong Answer [Your output: None  |  Expected Output: [25 -5]]
